[context.production.environment]
  HUGO_VERSION = "0.101.0"

  [[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  exclude = [
    # By file Path
    #'./build-dir/path-to/file.html',
    # By Glob pattern
    '**/page/**'
  ]
[build.environment]
  HUGO_VERSION = "0.101.0"
  
[[redirects]]
  from = "/ittea"
  to = "https://raw.githubusercontent.com/emadadel4/itt/refs/heads/main/itt.ps1"
  status = 301
  force = true
