[context.production.environment]
  HUGO_VERSION = "0.124.1"

  [[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  exclude = [
    # By file Path
    #'./build-dir/path-to/file.html',
    # By Glob pattern
    '**/page/**'
  ]
[build.environment]
  HUGO_VERSION = "0.124.1"

[[redirects]]
  from = "https://emadadel4.github.io/ittea"
  to = "https://raw.githubusercontent.com/emadadel4/itt/refs/heads/main/itt.ps1"
  status = 301
  force = true
